apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dotnet-app
  template:
    metadata:
      labels:
        app: dotnet-app
    spec:
      containers:
      - name: dotnet-app
        image: 794038238547.dkr.ecr.ap-south-1.amazonaws.com/dotnet-app:latest
        ports:
        - containerPort: 80